//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities
{
    using System;
    using System.Collections.Generic;
<<<<<<< HEAD
    
public partial class AspNetUser : SkyWeb.DatVM.Data.IEntity
{
}

}
=======
    
    public partial class AspNetUser : SkyWeb.DatVM.Data.IEntity
    {
    }
}
>>>>>>> dev-quyht-manageplace
