//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challenge
    {
        public int Id { get; set; }
        public int FromGroup { get; set; }
        public int ToGroup { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public int Status { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Group Group1 { get; set; }
    }
}
