
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSocialNetwork.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Follow
{

    public int Id { get; set; }

    public string UserId { get; set; }

    public string FollowerId { get; set; }

    public System.DateTime CreateDate { get; set; }

    public bool Active { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

}

}
