//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hobby
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int SportId { get; set; }
    
        public virtual Sport Sport { get; set; }
        public virtual User User { get; set; }
    }
}
