//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News()
        {
            this.NewsComments = new HashSet<NewsComment>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Title { get; set; }
        public string NewsContent { get; set; }
        public string Image { get; set; }
        public int CategoryId { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsComment> NewsComments { get; set; }
    }
}
