//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceImage
    {
        public int Id { get; set; }
        public int PlaceId { get; set; }
        public string Image { get; set; }
    
        public virtual Place Place { get; set; }
    }
}
