//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities
{
    using System;
    using System.Collections.Generic;
<<<<<<< HEAD
    
public partial class TimeBlock
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TimeBlock()
    {

        this.FieldPrices = new HashSet<FieldPrice>();

    }


    public int Id { get; set; }

    public int FieldId { get; set; }

    public System.TimeSpan StartTime { get; set; }

    public System.TimeSpan EndTime { get; set; }

    public double Price { get; set; }

    public bool Active { get; set; }



    public virtual Field Field { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FieldPrice> FieldPrices { get; set; }

}

}
=======
    
    public partial class TimeBlock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeBlock()
        {
            this.FieldPrices = new HashSet<FieldPrice>();
        }
    
        public int Id { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public double Price { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldPrice> FieldPrices { get; set; }
    }
}
>>>>>>> dev-quyht-manageplace
