//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IAspNetUserService : SkyWeb.DatVM.Data.IBaseService<AspNetUser>
    {
    }
    
    public partial class AspNetUserService : SkyWeb.DatVM.Data.BaseService<AspNetUser>, IAspNetUserService
    {
        public AspNetUserService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IAspNetUserRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
