//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IAspNetRoleService : SkyWeb.DatVM.Data.IBaseService<AspNetRole>
    {
    }
    
    public partial class AspNetRoleService : SkyWeb.DatVM.Data.BaseService<AspNetRole>, IAspNetRoleService
    {
        public AspNetRoleService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IAspNetRoleRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
