//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ICategoryService : SkyWeb.DatVM.Data.IBaseService<Category>
    {
    }
    
    public partial class CategoryService : SkyWeb.DatVM.Data.BaseService<Category>, ICategoryService
    {
        public CategoryService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ICategoryRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
