//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ICategorySportService : SkyWeb.DatVM.Data.IBaseService<CategorySport>
    {
    }
    
    public partial class CategorySportService : SkyWeb.DatVM.Data.BaseService<CategorySport>, ICategorySportService
    {
        public CategorySportService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ICategorySportRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
