
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSocialNetwork.Models.Entities.Services
{

using System;
    using System.Collections.Generic;
    

public partial interface IChallengeService : SkyWeb.DatVM.Data.IBaseService<Challenge>
{
}

public partial class ChallengeService : SkyWeb.DatVM.Data.BaseService<Challenge>, IChallengeService
{
    public ChallengeService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IChallengeRepository repository) : base(unitOfWork, repository)
    {
    }
}

}
