
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSocialNetwork.Models.Entities.Services
{

using System;
    using System.Collections.Generic;
    

public partial interface IEventService : SkyWeb.DatVM.Data.IBaseService<Event>
{
}

public partial class EventService : SkyWeb.DatVM.Data.BaseService<Event>, IEventService
{
    public EventService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IEventRepository repository) : base(unitOfWork, repository)
    {
    }
}

}
