
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSocialNetwork.Models.Entities.Services
{

using System;
    using System.Collections.Generic;
    

public partial interface IFieldPriceService : SkyWeb.DatVM.Data.IBaseService<FieldPrice>
{
}

public partial class FieldPriceService : SkyWeb.DatVM.Data.BaseService<FieldPrice>, IFieldPriceService
{
    public FieldPriceService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IFieldPriceRepository repository) : base(unitOfWork, repository)
    {
    }
}

}
