//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IFieldService : SkyWeb.DatVM.Data.IBaseService<Field>
    {
    }
    
    public partial class FieldService : SkyWeb.DatVM.Data.BaseService<Field>, IFieldService
    {
        public FieldService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IFieldRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
