//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IFieldTypeService : SkyWeb.DatVM.Data.IBaseService<FieldType>
    {
    }
    
    public partial class FieldTypeService : SkyWeb.DatVM.Data.BaseService<FieldType>, IFieldTypeService
    {
        public FieldTypeService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IFieldTypeRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
