
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSocialNetwork.Models.Entities.Services
{

using System;
    using System.Collections.Generic;
    

public partial interface IFirebaseTokenService : SkyWeb.DatVM.Data.IBaseService<FirebaseToken>
{
}

public partial class FirebaseTokenService : SkyWeb.DatVM.Data.BaseService<FirebaseToken>, IFirebaseTokenService
{
    public FirebaseTokenService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IFirebaseTokenRepository repository) : base(unitOfWork, repository)
    {
    }
}

}
