
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSocialNetwork.Models.Entities.Services
{

using System;
    using System.Collections.Generic;
    

public partial interface IFollowService : SkyWeb.DatVM.Data.IBaseService<Follow>
{
}

public partial class FollowService : SkyWeb.DatVM.Data.BaseService<Follow>, IFollowService
{
    public FollowService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IFollowRepository repository) : base(unitOfWork, repository)
    {
    }
}

}
