//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IGroupService : SkyWeb.DatVM.Data.IBaseService<Group>
    {
    }
    
    public partial class GroupService : SkyWeb.DatVM.Data.BaseService<Group>, IGroupService
    {
        public GroupService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IGroupRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
