
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSocialNetwork.Models.Entities.Services
{

using System;
    using System.Collections.Generic;
    

public partial interface IGroupMemberService : SkyWeb.DatVM.Data.IBaseService<GroupMember>
{
}

public partial class GroupMemberService : SkyWeb.DatVM.Data.BaseService<GroupMember>, IGroupMemberService
{
    public GroupMemberService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IGroupMemberRepository repository) : base(unitOfWork, repository)
    {
    }
}

}
