//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IHobbyService : SkyWeb.DatVM.Data.IBaseService<Hobby>
    {
    }
    
    public partial class HobbyService : SkyWeb.DatVM.Data.BaseService<Hobby>, IHobbyService
    {
        public HobbyService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IHobbyRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
