
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSocialNetwork.Models.Entities.Services
{

using System;
    using System.Collections.Generic;
    

public partial interface IInvitationService : SkyWeb.DatVM.Data.IBaseService<Invitation>
{
}

public partial class InvitationService : SkyWeb.DatVM.Data.BaseService<Invitation>, IInvitationService
{
    public InvitationService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IInvitationRepository repository) : base(unitOfWork, repository)
    {
    }
}

}
