//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface INewsCommentService : SkyWeb.DatVM.Data.IBaseService<NewsComment>
    {
    }
    
    public partial class NewsCommentService : SkyWeb.DatVM.Data.BaseService<NewsComment>, INewsCommentService
    {
        public NewsCommentService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.INewsCommentRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
