//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IParticipationService : SkyWeb.DatVM.Data.IBaseService<Participation>
    {
    }
    
    public partial class ParticipationService : SkyWeb.DatVM.Data.BaseService<Participation>, IParticipationService
    {
        public ParticipationService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IParticipationRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
