//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IPlaceImageService : SkyWeb.DatVM.Data.IBaseService<PlaceImage>
    {
    }
    
    public partial class PlaceImageService : SkyWeb.DatVM.Data.BaseService<PlaceImage>, IPlaceImageService
    {
        public PlaceImageService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IPlaceImageRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
