//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IPlaceService : SkyWeb.DatVM.Data.IBaseService<Place>
    {
    }
    
    public partial class PlaceService : SkyWeb.DatVM.Data.BaseService<Place>, IPlaceService
    {
        public PlaceService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IPlaceRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
