//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IPostCommentService : SkyWeb.DatVM.Data.IBaseService<PostComment>
    {
    }
    
    public partial class PostCommentService : SkyWeb.DatVM.Data.BaseService<PostComment>, IPostCommentService
    {
        public PostCommentService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IPostCommentRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
