
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSocialNetwork.Models.Entities.Services
{

using System;
    using System.Collections.Generic;
    

public partial interface IPostImageService : SkyWeb.DatVM.Data.IBaseService<PostImage>
{
}

public partial class PostImageService : SkyWeb.DatVM.Data.BaseService<PostImage>, IPostImageService
{
    public PostImageService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IPostImageRepository repository) : base(unitOfWork, repository)
    {
    }
}

}
