//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IPostService : SkyWeb.DatVM.Data.IBaseService<Post>
    {
    }
    
    public partial class PostService : SkyWeb.DatVM.Data.BaseService<Post>, IPostService
    {
        public PostService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IPostRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
