
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSocialNetwork.Models.Entities.Services
{

using System;
    using System.Collections.Generic;
    

public partial interface IUserService : SkyWeb.DatVM.Data.IBaseService<User>
{
}

public partial class UserService : SkyWeb.DatVM.Data.BaseService<User>, IUserService
{
    public UserService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IUserRepository repository) : base(unitOfWork, repository)
    {
    }
}

}
