
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSocialNetwork.Models.Entities.Repositories
{

using System;
    using System.Collections.Generic;
    

public partial interface IHobbyRepository : SkyWeb.DatVM.Data.IBaseRepository<Hobby>
{
}

public partial class HobbyRepository : SkyWeb.DatVM.Data.BaseRepository<Hobby>, IHobbyRepository
{
	public HobbyRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
    {
    }
}

}
