
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSocialNetwork.Models.Entities.Repositories
{

using System;
    using System.Collections.Generic;
    

public partial interface IInvitationRepository : SkyWeb.DatVM.Data.IBaseRepository<Invitation>
{
}

public partial class InvitationRepository : SkyWeb.DatVM.Data.BaseRepository<Invitation>, IInvitationRepository
{
	public InvitationRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
    {
    }
}

}
