
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSocialNetwork.Models.Entities.Repositories
{

using System;
    using System.Collections.Generic;
    

public partial interface INewsCommentRepository : SkyWeb.DatVM.Data.IBaseRepository<NewsComment>
{
}

public partial class NewsCommentRepository : SkyWeb.DatVM.Data.BaseRepository<NewsComment>, INewsCommentRepository
{
	public NewsCommentRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
    {
    }
}

}
