
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSocialNetwork.Models.Entities.Repositories
{

using System;
    using System.Collections.Generic;
    

public partial interface IParticipationRepository : SkyWeb.DatVM.Data.IBaseRepository<Participation>
{
}

public partial class ParticipationRepository : SkyWeb.DatVM.Data.BaseRepository<Participation>, IParticipationRepository
{
	public ParticipationRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
    {
    }
}

}
