
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSocialNetwork.Models.Entities.Repositories
{

using System;
    using System.Collections.Generic;
    

public partial interface IPlaceImageRepository : SkyWeb.DatVM.Data.IBaseRepository<PlaceImage>
{
}

public partial class PlaceImageRepository : SkyWeb.DatVM.Data.BaseRepository<PlaceImage>, IPlaceImageRepository
{
	public PlaceImageRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
    {
    }
}

}
