
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSocialNetwork.Models.Entities.Repositories
{

using System;
    using System.Collections.Generic;
    

public partial interface IPostImageRepository : SkyWeb.DatVM.Data.IBaseRepository<PostImage>
{
}

public partial class PostImageRepository : SkyWeb.DatVM.Data.BaseRepository<PostImage>, IPostImageRepository
{
	public PostImageRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
    {
    }
}

}
