//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChallengeViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<SportsSocialNetwork.Models.Entities.Challenge>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int FromGroup { get; set; }
    			public virtual int ToGroup { get; set; }
    			public virtual Nullable<bool> Accepted { get; set; }
    			public virtual int Status { get; set; }
    			public virtual string Description { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public ChallengeViewModel() : base() { }
    	public ChallengeViewModel(SportsSocialNetwork.Models.Entities.Challenge entity) : base(entity) { }
    
    }
}
