//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<SportsSocialNetwork.Models.Entities.Event>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int Name { get; set; }
    			public virtual string CreatorId { get; set; }
    			public virtual System.DateTime StartDate { get; set; }
    			public virtual System.DateTime EndDate { get; set; }
    			public virtual int PlaceId { get; set; }
    			public virtual string Description { get; set; }
    			public virtual string Image { get; set; }
    			public virtual int Status { get; set; }
    			public virtual bool Avtive { get; set; }
    	
    	public EventViewModel() : base() { }
    	public EventViewModel(SportsSocialNetwork.Models.Entities.Event entity) : base(entity) { }
    
    }
}
