//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<SportsSocialNetwork.Models.Entities.Group>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string Name { get; set; }
    			public virtual string Description { get; set; }
    			public virtual int SportId { get; set; }
    			public virtual string CoverImage { get; set; }
    			public virtual string Avatar { get; set; }
    			public virtual Nullable<bool> Active { get; set; }
    	
    	public GroupViewModel() : base() { }
    	public GroupViewModel(SportsSocialNetwork.Models.Entities.Group entity) : base(entity) { }
    
    }
}
