//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMemberViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<SportsSocialNetwork.Models.Entities.GroupMember>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int GroupId { get; set; }
    			public virtual string UserId { get; set; }
    			public virtual bool Admin { get; set; }
    			public virtual int Status { get; set; }
    	
    	public GroupMemberViewModel() : base() { }
    	public GroupMemberViewModel(SportsSocialNetwork.Models.Entities.GroupMember entity) : base(entity) { }
    
    }
}
