//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvitationViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<SportsSocialNetwork.Models.ViewModels.Invitation>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string SenderId { get; set; }
    			public virtual string InvitationContent { get; set; }
    			public virtual int CreateDate { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public InvitationViewModel() : base() { }
    	public InvitationViewModel(SportsSocialNetwork.Models.ViewModels.Invitation entity) : base(entity) { }
    
    }
}
