//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<SportsSocialNetwork.Models.Entities.Notification>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string UserId { get; set; }
    			public virtual string Title { get; set; }
    			public virtual string Message { get; set; }
    			public virtual int Type { get; set; }
    			public virtual int PostId { get; set; }
    			public virtual int InvitationId { get; set; }
    	
    	public NotificationViewModel() : base() { }
    	public NotificationViewModel(SportsSocialNetwork.Models.Entities.Notification entity) : base(entity) { }
    
    }
}
