//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipationViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<SportsSocialNetwork.Models.Entities.Participation>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int EventId { get; set; }
    			public virtual string UserId { get; set; }
    			public virtual int Type { get; set; }
    			public virtual string TeamName { get; set; }
    	
    	public ParticipationViewModel() : base() { }
    	public ParticipationViewModel(SportsSocialNetwork.Models.Entities.Participation entity) : base(entity) { }
    
    }
}
