//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<SportsSocialNetwork.Models.Entities.Place>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string UserId { get; set; }
    			public virtual string Name { get; set; }
    			public virtual string Email { get; set; }
    			public virtual string City { get; set; }
    			public virtual string District { get; set; }
    			public virtual string Ward { get; set; }
    			public virtual string Address { get; set; }
    			public virtual string PhoneNumber { get; set; }
    			public virtual string Description { get; set; }
    			public virtual double Latitude { get; set; }
    			public virtual double Longitude { get; set; }
    			public virtual int Status { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual System.TimeSpan StartTime { get; set; }
    			public virtual System.TimeSpan EndTime { get; set; }
    			public virtual bool Approve { get; set; }
    	
    	public PlaceViewModel() : base() { }
    	public PlaceViewModel(SportsSocialNetwork.Models.Entities.Place entity) : base(entity) { }
    
    }
}
