//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<SportsSocialNetwork.Models.ViewModels.Sport>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string Name { get; set; }
    	
    	public SportViewModel() : base() { }
    	public SportViewModel(SportsSocialNetwork.Models.ViewModels.Sport entity) : base(entity) { }
    
    }
}
