//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<SportsSocialNetwork.Models.Entities.User>
    {
    	
    			public virtual string Id { get; set; }
    			public virtual string City { get; set; }
    			public virtual string District { get; set; }
    			public virtual string Ward { get; set; }
    			public virtual string Address { get; set; }
    			public virtual string AvatarImage { get; set; }
    			public virtual string CoverImage { get; set; }
    			public virtual System.DateTime Birthday { get; set; }
    			public virtual int Gender { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual int RoleId { get; set; }
    			public virtual System.DateTime CreateDate { get; set; }
    	
    	public UserViewModel() : base() { }
    	public UserViewModel(SportsSocialNetwork.Models.Entities.User entity) : base(entity) { }
    
    }
}
