//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSocialNetwork.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInvitationViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<SportsSocialNetwork.Models.Entities.UserInvitation>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int InvitationId { get; set; }
    			public virtual string ReciverId { get; set; }
    			public virtual Nullable<bool> Accept { get; set; }
    	
    	public UserInvitationViewModel() : base() { }
    	public UserInvitationViewModel(SportsSocialNetwork.Models.Entities.UserInvitation entity) : base(entity) { }
    
    }
}
